In [81]:
import numpy as np
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #Задаємо матрицю 3*3
print(m_sqr_arr)
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #Ще один варіант як задати матрицю
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
#Побудуємо діагональ
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
diag = np.diag(m_sqr_mx)
print(diag)

[1 5 9]


In [53]:
#Побудуємо діагональну матрицю на базі полученої діагоналі
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

        
    

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [54]:
#Транспонована матриця
a = np.matrix('1 2 3; 4 5 6')
print('A=',a)
a_t = a.transpose()
print(a_t)
    

A= [[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [56]:
print(a.T) # ще один способ транспонування матриці

[[1 4]
 [2 5]
 [3 6]]


In [58]:
a = np.matrix('1 2; 3 4')
a_det = np.linalg.det(a) #Визначник матриці
print(format(a_det, '.9g'))


-2


In [66]:
#Множення матриці на число 
a = np.matrix('1 2 3; 4 5 6')
c = 3 * a
print(c)


[[ 3  6  9]
 [12 15 18]]


In [67]:
#Додавання матриць
a = np.matrix('1 6 3; 8 2 7')
b = np.matrix('8 1 5; 6 9 12')
c = a + b
print(c)

[[ 9  7  8]
 [14 11 19]]


In [68]:
#Добуток матриць
a = np.matrix('1 2 3; 4 5 6')
b = np.matrix('7 8; 9 1; 2 3')
c = a.dot(b)
print(c)


[[31 19]
 [85 55]]


In [69]:
#детермінант (визначник матриці)
a = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(a)
np.linalg.det(a)


[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


-14.000000000000009

In [ ]:
# Обернена матриця
a = np.matrix('1 -3; 2 5')
a_inv = np.linalg.inv(a)
print(a_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [71]:
#Ранг матриці
rank = np.linalg.matrix_rank(a)
print(rank)


2


In [72]:
#Матричний метод
a = np.matrix('3 -1 2; 1 4 -1; 2 3 1')
b = np.matrix('-4; 10; 8')
print('A=', a)
print('B=',b)
a_inv = np.linalg.inv(a)
print(a_inv)
x = a_inv.dot(b)
print('X=',x)



A= [[ 3 -1  2]
 [ 1  4 -1]
 [ 2  3  1]]
B= [[-4]
 [10]
 [ 8]]
[[ 0.5         0.5        -0.5       ]
 [-0.21428571 -0.07142857  0.35714286]
 [-0.35714286 -0.78571429  0.92857143]]
X= [[-1.]
 [ 3.]
 [ 1.]]


In [85]:
#Метод Крамера
a = np.matrix('3 -1 2; 1 4 -1; 2 3 1')
print('A=',a)
b = np.matrix('-4; 10; 8')
print('B=',b)

def kramer (a, b):
    a_det = np.linalg.det(A)
    print('Детермінант матриці = ', a_det)
#Зробити реревірку,що детермінант не дорівнює нулю
    if (a_det != 0):
        print ('Розв*язуємо систему')
        
        x_m = np.matrix(a)
        x_m[:, 0] = b # 1 cт. замінюємо на  ст.b
        print('x_m=', x_m)
        y_m = np.matrix(a)
        y_m[:, 1] = b # 2 cт. замінюємо на  ст.b
        print('y_m=',y_m)

        z_m = np.matrix(a)
        z_m[:, 2] = b # 3 cт. замінюємо на  ст.b
        print('z_m=',z_m)

        x = np.linalg.det(x_m) / a_det
        y = np.linalg.det(y_m) / a_det
        z = np.linalg.det(z_m) / a_det
        print('X = ', round(x,5))

        print('Y=', round(y,5))

        print('Z=', round(z,5))
    else:
        print('Розв*язків немає')
kramer(a,b)


A= [[ 3 -1  2]
 [ 1  4 -1]
 [ 2  3  1]]
B= [[-4]
 [10]
 [ 8]]
Детермінант матриці =  13.999999999999996
Розв*язуємо систему
x_m= [[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
y_m= [[ 3 -4  2]
 [ 1 10 -1]
 [ 2  8  1]]
z_m= [[ 3 -1 -4]
 [ 1  4 10]
 [ 2  3  8]]
X =  -1.0
Y= 3.0
Z= 1.0


In [80]:
#Перевірка за допомогою  solve() пакету linalg:
X = np.linalg.solve(a, b)
print('Перевірка X=',X)

Перевірка X= [[-1.]
 [ 3.]
 [ 1.]]
